# Mmulti-Linear Regression

In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score,mean_absolute_error   
from sklearn.datasets import make_regression

In [2]:
X,y = make_regression(n_samples=100, n_features=2,n_informative=2, noise=50, random_state=42)

In [3]:
df = pd.DataFrame({'feature1':X[:,0], 'feature2':X[:,1], 'target':y})

In [4]:
df

    feature1  feature2      target
0  -1.191303  0.656554  -22.779796
1   0.058209 -1.142970 -107.569629
2   0.586857  2.190456  201.122932
3   0.473238 -0.072829    1.480178
4   0.738467  0.171368  111.798503
..       ...       ...         ...
95  0.361396  1.538037  154.963515
96  0.296120  0.261055  -17.725247
97 -0.990536 -0.566298 -191.245708
98 -0.460639  1.057122   92.340622
99  0.259883  0.781823   31.640969

[100 rows x 3 columns]

In [5]:
fig = px.scatter_3d(df,x='feature1', y='feature2', z='target')
fig.show()

In [6]:
x_train, x_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [8]:
print(len(x_train), len(x_test))

80 20

In [10]:
lr = LinearRegression()
lr.fit(x_train, y_train)

LinearRegression()

In [11]:
y_pred = lr.predict(x_test)

In [12]:
data = pd.DataFrame({'Actual':y_test, 'Predicted':y_pred})

In [13]:
data

        Actual   Predicted
0   -15.737077  -51.229174
1    24.752490    1.574796
2    72.577907   85.267372
3   -91.595863  -22.769528
4    77.746425   63.793614
5   221.753212  107.715830
6   148.513784  182.902199
7   -11.108155 -124.008040
8  -218.258102 -175.016170
9   -22.779796  -48.393879
10   47.605042   77.934556
11 -144.918846 -135.456526
12  174.943943  112.828620
13  -38.968809  -37.750061
14   79.671288  110.157418
15  111.798503   72.196625
16   52.089653  -21.530476
17 -160.024923   -1.423024
18 -112.947440  -69.096035
19   75.218972   42.046309

In [15]:
print('Mean Squared Error:', mean_squared_error(y_test, y_pred))
print('R^2 Score:', r2_score(y_test, y_pred))       
print('rmse:', np.sqrt(mean_squared_error(y_test, y_pred)))
print('MAE:', mean_absolute_error(y_test, y_pred))

Mean Squared Error: 3865.69317237263
R^2 Score: 0.6996264436675446
rmse: 62.174698812078134
MAE: 48.33900535327827

In [1]:
df

NameError: name 'df' is not defined